apiVersion: v2
name: flipt
home: https://flipt.io
description: Flipt is an open-source, self-hosted feature flag solution.
type: application
version: 0.70.1
appVersion: v1.50.0
maintainers:
  - name: Flipt
    url: https://github.com/flipt-io/helm-charts
