apiVersion: v2
name: flipt
home: https://flipt.io
description: Flipt is an open-source, self-hosted feature flag solution.
type: application
version: 0.57.0
appVersion: v1.39.2
maintainers:
  - name: Flipt
    url: https://github.com/flipt-io/helm-charts
